//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlacIntegrityCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlacIntegrityCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Browse.
        /// </summary>
        internal static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Type.
        /// </summary>
        internal static string GroupBoxDriveType {
            get {
                return ResourceManager.GetString("GroupBoxDriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string GroupBoxLog {
            get {
                return ResourceManager.GetString("GroupBoxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log output mode.
        /// </summary>
        internal static string GroupBoxLogOutput {
            get {
                return ResourceManager.GetString("GroupBoxLogOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string GroupBoxSettings {
            get {
                return ResourceManager.GetString("GroupBoxSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        internal static string LabelFolder {
            get {
                return ResourceManager.GetString("LabelFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} files..
        /// </summary>
        internal static string LogCount {
            get {
                return ResourceManager.GetString("LogCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting files in &quot;{0}&quot;....
        /// </summary>
        internal static string LogCountingFiles {
            get {
                return ResourceManager.GetString("LogCountingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished. Corrupted FLAC files = {0}, Elapsed time = {1}.
        /// </summary>
        internal static string LogFinished {
            get {
                return ResourceManager.GetString("LogFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrity Checking....
        /// </summary>
        internal static string LogIntegrityChecking {
            get {
                return ResourceManager.GetString("LogIntegrityChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _HDD (Check files one by one).
        /// </summary>
        internal static string RadioHdd {
            get {
                return ResourceManager.GetString("RadioHdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Concise.
        /// </summary>
        internal static string RadioLogConcise {
            get {
                return ResourceManager.GetString("RadioLogConcise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Verbose.
        /// </summary>
        internal static string RadioLogVerbose {
            get {
                return ResourceManager.GetString("RadioLogVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS_D or RAID (Check files in parallel).
        /// </summary>
        internal static string RadioSsd {
            get {
                return ResourceManager.GetString("RadioSsd", resourceCulture);
            }
        }
    }
}
