//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavFormatConv.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WavFormatConv.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Replace bext chunk.
        /// </summary>
        internal static string ButtonBext {
            get {
                return ResourceManager.GetString("ButtonBext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Browse ....
        /// </summary>
        internal static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bro_wse ....
        /// </summary>
        internal static string ButtonBrowseWriteFile {
            get {
                return ResourceManager.GetString("ButtonBrowseWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Chunk ....
        /// </summary>
        internal static string ButtonChunkAdd {
            get {
                return ResourceManager.GetString("ButtonChunkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete Selected Chunk.
        /// </summary>
        internal static string ButtonChunkDelete {
            get {
                return ResourceManager.GetString("ButtonChunkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move D_own Selected Chunk.
        /// </summary>
        internal static string ButtonChunkMoveDown {
            get {
                return ResourceManager.GetString("ButtonChunkMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move _Up Selected Chunk.
        /// </summary>
        internal static string ButtonChunkMoveUp {
            get {
                return ResourceManager.GetString("ButtonChunkMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Replace ds64 chunk.
        /// </summary>
        internal static string ButtonDS64 {
            get {
                return ResourceManager.GetString("ButtonDS64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Replace id3 chunk.
        /// </summary>
        internal static string ButtonID3 {
            get {
                return ResourceManager.GetString("ButtonID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Browse ....
        /// </summary>
        internal static string buttonID3BrowseImage {
            get {
                return ResourceManager.GetString("buttonID3BrowseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add JUNK chunk.
        /// </summary>
        internal static string ButtonJunk {
            get {
                return ResourceManager.GetString("ButtonJunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start Conversion.
        /// </summary>
        internal static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set chunkSize longer than actual data size.
        /// </summary>
        internal static string CheckBoxDataLonger {
            get {
                return ResourceManager.GetString("CheckBoxDataLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add garbage on file footer.
        /// </summary>
        internal static string CheckBoxRiffAddGarbage {
            get {
                return ResourceManager.GetString("CheckBoxRiffAddGarbage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set chunkSize longer than actual file size.
        /// </summary>
        internal static string CheckBoxRiffLonger {
            get {
                return ResourceManager.GetString("CheckBoxRiffLonger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Input file and Output file must be different file.
        /// </summary>
        internal static string ErrorInputAndOutputIsTheSame {
            get {
                return ResourceManager.GetString("ErrorInputAndOutputIsTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bext chunk.
        /// </summary>
        internal static string GroupBoxBext {
            get {
                return ResourceManager.GetString("GroupBoxBext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk layout.
        /// </summary>
        internal static string GroupBoxChunkLayout {
            get {
                return ResourceManager.GetString("GroupBoxChunkLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA chunk.
        /// </summary>
        internal static string GroupBoxData {
            get {
                return ResourceManager.GetString("GroupBoxData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ds64 chunk.
        /// </summary>
        internal static string GroupBoxDS64 {
            get {
                return ResourceManager.GetString("GroupBoxDS64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fmt chunk.
        /// </summary>
        internal static string GroupBoxFmt {
            get {
                return ResourceManager.GetString("GroupBoxFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id3 chunk.
        /// </summary>
        internal static string GroupBoxID3 {
            get {
                return ResourceManager.GetString("GroupBoxID3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUNK chunk.
        /// </summary>
        internal static string GroupBoxJunk {
            get {
                return ResourceManager.GetString("GroupBoxJunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read WAV File.
        /// </summary>
        internal static string GroupBoxReadFile {
            get {
                return ResourceManager.GetString("GroupBoxReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIFF chunk.
        /// </summary>
        internal static string GroupBoxRiff {
            get {
                return ResourceManager.GetString("GroupBoxRiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string GroupBoxSettings {
            get {
                return ResourceManager.GetString("GroupBoxSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write WAV File.
        /// </summary>
        internal static string GroupBoxWriteFile {
            get {
                return ResourceManager.GetString("GroupBoxWriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album cover art filename:.
        /// </summary>
        internal static string LabelAlbumCoverArtFile {
            get {
                return ResourceManager.GetString("LabelAlbumCoverArtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read succeeded: {0}.
        /// </summary>
        internal static string LogReadSucceeded {
            get {
                return ResourceManager.GetString("LogReadSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write succeeded: {0}.
        /// </summary>
        internal static string LogWriteSucceeded {
            get {
                return ResourceManager.GetString("LogWriteSucceeded", resourceCulture);
            }
        }
    }
}
