//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecPcmWin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecPcmWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Memory allocation failed: please reduce recording buffer size.
        /// </summary>
        internal static string ErrorCouldNotAllocateMemory {
            get {
                return ResourceManager.GetString("ErrorCouldNotAllocateMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Num of channels must be integer number larger than 1.
        /// </summary>
        internal static string ErrorNumChannels {
            get {
                return ResourceManager.GetString("ErrorNumChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Recording buffer size must be larger than 0 and smaller than 2097151.
        /// </summary>
        internal static string ErrorRecordingBufferSize {
            get {
                return ResourceManager.GetString("ErrorRecordingBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Wasapi buffer size must be integer number greater than 0.
        /// </summary>
        internal static string ErrorWasapiBufferSize {
            get {
                return ResourceManager.GetString("ErrorWasapiBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Driven (_E).
        /// </summary>
        internal static string EventDriven {
            get {
                return ResourceManager.GetString("EventDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Available formats (_A).
        /// </summary>
        internal static string MainAvailableFormats {
            get {
                return ResourceManager.GetString("MainAvailableFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set dwChannelMask.
        /// </summary>
        internal static string MainCheckboxSetDwChannelMask {
            get {
                return ResourceManager.GetString("MainCheckboxSetDwChannelMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect (_D).
        /// </summary>
        internal static string MainDeselect {
            get {
                return ResourceManager.GetString("MainDeselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        internal static string MainDisplaySettings {
            get {
                return ResourceManager.GetString("MainDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DwChannelMask settings.
        /// </summary>
        internal static string MainGroupBoxDwChannelMask {
            get {
                return ResourceManager.GetString("MainGroupBoxDwChannelMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Endpoint Master Volume Control.
        /// </summary>
        internal static string MainGroupBoxMasterVolumeControl {
            get {
                return ResourceManager.GetString("MainGroupBoxMasterVolumeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string MainLanguage {
            get {
                return ResourceManager.GetString("MainLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Meter.
        /// </summary>
        internal static string MainLevelMeter {
            get {
                return ResourceManager.GetString("MainLevelMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update while recording.
        /// </summary>
        internal static string MainLevelMeterUpdateWhileRecording {
            get {
                return ResourceManager.GetString("MainLevelMeterUpdateWhileRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Recording Devices.
        /// </summary>
        internal static string MainListOfRecordingDevices {
            get {
                return ResourceManager.GetString("MainListOfRecordingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string MainLog {
            get {
                return ResourceManager.GetString("MainLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num of Channels.
        /// </summary>
        internal static string MainNumOfChannels {
            get {
                return ResourceManager.GetString("MainNumOfChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Mode.
        /// </summary>
        internal static string MainOperationMode {
            get {
                return ResourceManager.GetString("MainOperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantization Bit Rate.
        /// </summary>
        internal static string MainQuantizationBitRate {
            get {
                return ResourceManager.GetString("MainQuantizationBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record (_R).
        /// </summary>
        internal static string MainRecord {
            get {
                return ResourceManager.GetString("MainRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Control.
        /// </summary>
        internal static string MainRecordingControl {
            get {
                return ResourceManager.GetString("MainRecordingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Data Size.
        /// </summary>
        internal static string MainRecordingDataSize {
            get {
                return ResourceManager.GetString("MainRecordingDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Rate (Hz).
        /// </summary>
        internal static string MainSampleRate {
            get {
                return ResourceManager.GetString("MainSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select (_L).
        /// </summary>
        internal static string MainSelect {
            get {
                return ResourceManager.GetString("MainSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop (_S).
        /// </summary>
        internal static string MainStop {
            get {
                return ResourceManager.GetString("MainStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASAPI Buffer Size.
        /// </summary>
        internal static string MainWasapiBufferSize {
            get {
                return ResourceManager.GetString("MainWasapiBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASAPI Settings.
        /// </summary>
        internal static string MainWasapiSettings {
            get {
                return ResourceManager.GetString("MainWasapiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file Failed.
        /// </summary>
        internal static string SaveFileFailed {
            get {
                return ResourceManager.GetString("SaveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file Succeeded.
        /// </summary>
        internal static string SaveFileSucceeded {
            get {
                return ResourceManager.GetString("SaveFileSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Driven (_T).
        /// </summary>
        internal static string TimerDriven {
            get {
                return ResourceManager.GetString("TimerDriven", resourceCulture);
            }
        }
    }
}
