//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayPcmWin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayPcmWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Sound Effects.
        /// </summary>
        internal static string AudioFilterActivated {
            get {
                return ResourceManager.GetString("AudioFilterActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Sound Effects.
        /// </summary>
        internal static string AudioFilterAvailable {
            get {
                return ResourceManager.GetString("AudioFilterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Mapping.
        /// </summary>
        internal static string AudioFilterChannelMapping {
            get {
                return ResourceManager.GetString("AudioFilterChannelMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string AudioFilterClear {
            get {
                return ResourceManager.GetString("AudioFilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-emphasis (for 44.1kHz PCM playback).
        /// </summary>
        internal static string AudioFilterDeEmphasis {
            get {
                return ResourceManager.GetString("AudioFilterDeEmphasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string AudioFilterDelay {
            get {
                return ResourceManager.GetString("AudioFilterDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaural mix (forPCM).
        /// </summary>
        internal static string AudioFilterMonauralMix {
            get {
                return ResourceManager.GetString("AudioFilterMonauralMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Channel.
        /// </summary>
        internal static string AudioFilterMuteChannel {
            get {
                return ResourceManager.GetString("AudioFilterMuteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Channel {0}.
        /// </summary>
        internal static string AudioFilterMuteChannelDesc {
            get {
                return ResourceManager.GetString("AudioFilterMuteChannelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Polarity.
        /// </summary>
        internal static string AudioFilterPolarityInvert {
            get {
                return ResourceManager.GetString("AudioFilterPolarityInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Polarity : Channel {0}.
        /// </summary>
        internal static string AudioFilterPolarityInvertDesc {
            get {
                return ResourceManager.GetString("AudioFilterPolarityInvertDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the channel selected.
        /// </summary>
        internal static string AudioFilterSoloChannel {
            get {
                return ResourceManager.GetString("AudioFilterSoloChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the channel {0}.
        /// </summary>
        internal static string AudioFilterSoloChannelDesc {
            get {
                return ResourceManager.GetString("AudioFilterSoloChannelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOH NOSDAC high frequency roll-off compensation (PCM).
        /// </summary>
        internal static string AudioFilterZohNosdacCompensation {
            get {
                return ResourceManager.GetString("AudioFilterZohNosdacCompensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string ButtonSoundEffectsSettings {
            get {
                return ResourceManager.GetString("ButtonSoundEffectsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry... Please stop playback to add files to the playlist..
        /// </summary>
        internal static string CannotAddFile {
            get {
                return ResourceManager.GetString("CannotAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Mapping Table.
        /// </summary>
        internal static string ChannelMappingChannelMappingTable {
            get {
                return ResourceManager.GetString("ChannelMappingChannelMappingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of input channels:.
        /// </summary>
        internal static string ChannelMappingNumOfInputChannels {
            get {
                return ResourceManager.GetString("ChannelMappingNumOfInputChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable DSP.
        /// </summary>
        internal static string CheckBoxSoundEffects {
            get {
                return ResourceManager.GetString("CheckBoxSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipped sample value detected on floating point PCM data!
        ///  Clipped sample value count={1}, FileName={0}
        ///.
        /// </summary>
        internal static string ClippedSampleDetected {
            get {
                return ResourceManager.GetString("ClippedSampleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceStateChanged. DeviceId={0}.
        /// </summary>
        internal static string DeviceStateChanged {
            get {
                return ResourceManager.GetString("DeviceStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some kind of data is dropped but the data is not file nor folder. Failed to process dropped items..
        /// </summary>
        internal static string DroppedDataIsNotFile {
            get {
                return ResourceManager.GetString("DroppedDataIsNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code.
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter file version number mismatch.
        /// </summary>
        internal static string ErrorFilterFileVersionMismatch {
            get {
                return ResourceManager.GetString("ErrorFilterFileVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event driven.
        /// </summary>
        internal static string EventDriven {
            get {
                return ResourceManager.GetString("EventDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive.
        /// </summary>
        internal static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUE files|*.CUE.
        /// </summary>
        internal static string FilterCueFiles {
            get {
                return ResourceManager.GetString("FilterCueFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3U files|*.M3U;*.M3U8.
        /// </summary>
        internal static string FilterM3uFiles {
            get {
                return ResourceManager.GetString("FilterM3uFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPWPL files|*.PPWPL.
        /// </summary>
        internal static string FilterPpwplFiles {
            get {
                return ResourceManager.GetString("FilterPpwplFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported files|*.WAV;*.WAVE;*.FLAC;*.AIF;*.AIFF;*.AIFC;*.AIFFC;*.DSF;*.DFF;*.MP3;*.CUE;*.PPWPL;*.M3U;*.M3U8|WAVE files|*.WAV;*.WAVE|FLAC files|*.FLAC|AIFF files|*.AIF;*.AIFF;*.AIFC;*AIFFC|DSF files|*.DSF|DFF files|*.DFF|MP3 files|*.MP3|CUE files|*.CUE|PPWPL files|*.PPWPL|M3U files|*.M3U;*.M3U8|All files|*.*.
        /// </summary>
        internal static string FilterSupportedFiles {
            get {
                return ResourceManager.GetString("FilterSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        internal static string FloatingPointNumbers {
            get {
                return ResourceManager.GetString("FloatingPointNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Effects.
        /// </summary>
        internal static string GroupBoxSoundEffects {
            get {
                return ResourceManager.GetString("GroupBoxSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency.
        /// </summary>
        internal static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C)  2010 yamamoto2002
        ///
        ///■Special Thanks■
        ///Simplified-chinese localization: Tsong Zhang
        ///
        ///PlayPcmWin uses libFLAC.
        ///libFLAC license is a New BSD License. libFlacLicense.txt on the PlayPcmWin.exe folder contains full text of license.
        ///
        ///PlayPcmWin uses Jcode.pm character encoding detect function.
        ///Jcode.pm copyright is as follows: Copyright 1999-2005 Dan Kogai.
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear the playlist.
        /// </summary>
        internal static string MainButtonClearPlayList {
            get {
                return ResourceManager.GetString("MainButtonClearPlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delist the selected file(_R).
        /// </summary>
        internal static string MainButtonDelistSelected {
            get {
                return ResourceManager.GetString("MainButtonDelistSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L_ist supported formats.
        /// </summary>
        internal static string MainButtonInspectDevice {
            get {
                return ResourceManager.GetString("MainButtonInspectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string MainButtonNext {
            get {
                return ResourceManager.GetString("MainButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa_use.
        /// </summary>
        internal static string MainButtonPause {
            get {
                return ResourceManager.GetString("MainButtonPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Play.
        /// </summary>
        internal static string MainButtonPlay {
            get {
                return ResourceManager.GetString("MainButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string MainButtonPrev {
            get {
                return ResourceManager.GetString("MainButtonPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume(_U).
        /// </summary>
        internal static string MainButtonResume {
            get {
                return ResourceManager.GetString("MainButtonResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Detailed settings....
        /// </summary>
        internal static string MainButtonSettings {
            get {
                return ResourceManager.GetString("MainButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop.
        /// </summary>
        internal static string MainButtonStop {
            get {
                return ResourceManager.GetString("MainButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear the playlist.
        /// </summary>
        internal static string MainCMenuPlaylistClear {
            get {
                return ResourceManager.GetString("MainCMenuPlaylistClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist item edit mode(_E).
        /// </summary>
        internal static string MainCMenuPlayListEditMode {
            get {
                return ResourceManager.GetString("MainCMenuPlayListEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album name.
        /// </summary>
        internal static string MainDataGridColumnAlbumTitle {
            get {
                return ResourceManager.GetString("MainDataGridColumnAlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        internal static string MainDataGridColumnArtist {
            get {
                return ResourceManager.GetString("MainDataGridColumnArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitrate.
        /// </summary>
        internal static string MainDataGridColumnBitRate {
            get {
                return ResourceManager.GetString("MainDataGridColumnBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        internal static string MainDataGridColumnComposer {
            get {
                return ResourceManager.GetString("MainDataGridColumnComposer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string MainDataGridColumnDuration {
            get {
                return ResourceManager.GetString("MainDataGridColumnDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extension.
        /// </summary>
        internal static string MainDataGridColumnFileExtension {
            get {
                return ResourceManager.GetString("MainDataGridColumnFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string MainDataGridColumnIndexNr {
            get {
                return ResourceManager.GetString("MainDataGridColumnIndexNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of channels.
        /// </summary>
        internal static string MainDataGridColumnNumChannels {
            get {
                return ResourceManager.GetString("MainDataGridColumnNumChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantization bit rate.
        /// </summary>
        internal static string MainDataGridColumnQuantizationBitRate {
            get {
                return ResourceManager.GetString("MainDataGridColumnQuantizationBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch read endpoint.
        /// </summary>
        internal static string MainDataGridColumnReadSeparaterAfter {
            get {
                return ResourceManager.GetString("MainDataGridColumnReadSeparaterAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample rate.
        /// </summary>
        internal static string MainDataGridColumnSampleRate {
            get {
                return ResourceManager.GetString("MainDataGridColumnSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string MainDataGridColumnTitle {
            get {
                return ResourceManager.GetString("MainDataGridColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MainExpanderSettings {
            get {
                return ResourceManager.GetString("MainExpanderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string MainGroupBoxLog {
            get {
                return ResourceManager.GetString("MainGroupBoxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output device.
        /// </summary>
        internal static string MainGroupBoxOutputDevices {
            get {
                return ResourceManager.GetString("MainGroupBoxOutputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback control.
        /// </summary>
        internal static string MainGroupBoxPlaybackControl {
            get {
                return ResourceManager.GetString("MainGroupBoxPlaybackControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist(Drop audio files from Explorer to add files).
        /// </summary>
        internal static string MainGroupBoxPlaylist {
            get {
                return ResourceManager.GetString("MainGroupBoxPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data feed mode.
        /// </summary>
        internal static string MainGroupBoxWasapiDataFeedMode {
            get {
                return ResourceManager.GetString("MainGroupBoxWasapiDataFeedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation mode.
        /// </summary>
        internal static string MainGroupBoxWasapiOperationMode {
            get {
                return ResourceManager.GetString("MainGroupBoxWasapiOperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output latency.
        /// </summary>
        internal static string MainGroupBoxWasapiOutputLatency {
            get {
                return ResourceManager.GetString("MainGroupBoxWasapiOutputLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASAPI settings.
        /// </summary>
        internal static string MainGroupBoxWasapiSettings {
            get {
                return ResourceManager.GetString("MainGroupBoxWasapiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tracks.
        /// </summary>
        internal static string MainPlayModeAllTracks {
            get {
                return ResourceManager.GetString("MainPlayModeAllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tracks repeat.
        /// </summary>
        internal static string MainPlayModeAllTracksRepeat {
            get {
                return ResourceManager.GetString("MainPlayModeAllTracksRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One track.
        /// </summary>
        internal static string MainPlayModeOneTrack {
            get {
                return ResourceManager.GetString("MainPlayModeOneTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One track repeat.
        /// </summary>
        internal static string MainPlayModeOneTrackRepeat {
            get {
                return ResourceManager.GetString("MainPlayModeOneTrackRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        internal static string MainPlayModeShuffle {
            get {
                return ResourceManager.GetString("MainPlayModeShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle repeat.
        /// </summary>
        internal static string MainPlayModeShuffleRepeat {
            get {
                return ResourceManager.GetString("MainPlayModeShuffleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event driven.
        /// </summary>
        internal static string MainRadioButtonEventDriven {
            get {
                return ResourceManager.GetString("MainRadioButtonEventDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive.
        /// </summary>
        internal static string MainRadioButtonExclusive {
            get {
                return ResourceManager.GetString("MainRadioButtonExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string MainRadioButtonShared {
            get {
                return ResourceManager.GetString("MainRadioButtonShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer driven.
        /// </summary>
        internal static string MainRadioButtonTimerDriven {
            get {
                return ResourceManager.GetString("MainRadioButtonTimerDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading files....
        /// </summary>
        internal static string MainStatusChangingPlayGroup {
            get {
                return ResourceManager.GetString("MainStatusChangingPlayGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused..
        /// </summary>
        internal static string MainStatusPaused {
            get {
                return ResourceManager.GetString("MainStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing..
        /// </summary>
        internal static string MainStatusPlaying {
            get {
                return ResourceManager.GetString("MainStatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create the playlist..
        /// </summary>
        internal static string MainStatusPleaseCreatePlaylist {
            get {
                return ResourceManager.GetString("MainStatusPleaseCreatePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more files to the playlist or Press play button.
        /// </summary>
        internal static string MainStatusPressPlayButton {
            get {
                return ResourceManager.GetString("MainStatusPressPlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read completed. ready to play..
        /// </summary>
        internal static string MainStatusReadCompleted {
            get {
                return ResourceManager.GetString("MainStatusReadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading PCM from file and arranging decoded PCM to main memory....
        /// </summary>
        internal static string MainStatusReadingFiles {
            get {
                return ResourceManager.GetString("MainStatusReadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading DSD from file and building DoP data onto main memory....
        /// </summary>
        internal static string MainStatusReadingFilesDoP {
            get {
                return ResourceManager.GetString("MainStatusReadingFilesDoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading playlist....
        /// </summary>
        internal static string MainStatusReadingPlaylist {
            get {
                return ResourceManager.GetString("MainStatusReadingPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        internal static string MainStatusStopping {
            get {
                return ResourceManager.GetString("MainStatusStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 sum validation failed! File may be corrupted: {0}
        ///  MD5 in metadata    = {1}
        ///  MD5 from PCM data= {2}.
        /// </summary>
        internal static string MD5SumMismatch {
            get {
                return ResourceManager.GetString("MD5SumMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not have STREAMINFO MD5 signature. Could not perform MD5 validation: {0}
        ///  MD5 from PCM data= {1}.
        /// </summary>
        internal static string MD5SumNotAvailable {
            get {
                return ResourceManager.GetString("MD5SumNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5sum validation succeeded. {0}.
        /// </summary>
        internal static string MD5SumValid {
            get {
                return ResourceManager.GetString("MD5SumValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory exhausted. Please reduce files on playlist..
        /// </summary>
        internal static string MemoryExhausted {
            get {
                return ResourceManager.GetString("MemoryExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string MenuItemFileExit {
            get {
                return ResourceManager.GetString("MenuItemFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the playlist(_N).
        /// </summary>
        internal static string MenuItemFileNew {
            get {
                return ResourceManager.GetString("MenuItemFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        internal static string MenuItemFileOpen {
            get {
                return ResourceManager.GetString("MenuItemFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        internal static string MenuItemFileSaveAs {
            get {
                return ResourceManager.GetString("MenuItemFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the playlist as a _CUE sheet....
        /// </summary>
        internal static string MenuItemFileSaveCueAs {
            get {
                return ResourceManager.GetString("MenuItemFileSaveCueAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About(_V).
        /// </summary>
        internal static string MenuItemHelpAbout {
            get {
                return ResourceManager.GetString("MenuItemHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit PlayPcmWin _Website.
        /// </summary>
        internal static string MenuItemHelpWeb {
            get {
                return ResourceManager.GetString("MenuItemHelpWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear the playlist.
        /// </summary>
        internal static string MenuItemPlayListClear {
            get {
                return ResourceManager.GetString("MenuItemPlayListClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist item edit mode(_E).
        /// </summary>
        internal static string MenuItemPlayListItemEditMode {
            get {
                return ResourceManager.GetString("MenuItemPlayListItemEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        internal static string MenuItemToolSettings {
            get {
                return ResourceManager.GetString("MenuItemToolSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P_laylist.
        /// </summary>
        internal static string MenuPlayList {
            get {
                return ResourceManager.GetString("MenuPlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        internal static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to store .
        /// </summary>
        internal static string NothingToStore {
            get {
                return ResourceManager.GetString("NothingToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported file format.
        /// </summary>
        internal static string NotSupportedFileFormat {
            get {
                return ResourceManager.GetString("NotSupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported quantization bit rate. supported formats are 16, 24 32 and 64.
        /// </summary>
        internal static string NotSupportedQuantizationBitRate {
            get {
                return ResourceManager.GetString("NotSupportedQuantizationBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play completed. elapsed time is.
        /// </summary>
        internal static string PlayCompletedElapsedTimeIs {
            get {
                return ResourceManager.GetString("PlayCompletedElapsedTimeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play start failed.
        /// </summary>
        internal static string PlayStartFailed {
            get {
                return ResourceManager.GetString("PlayStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read error.
        /// </summary>
        internal static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read failed files.
        /// </summary>
        internal static string ReadFailedFiles {
            get {
                return ResourceManager.GetString("ReadFailedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read {0} file failed .
        /// </summary>
        internal static string ReadFileFailed {
            get {
                return ResourceManager.GetString("ReadFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read playgroup {0} completed. Elapsed time: {1}ms.
        /// </summary>
        internal static string ReadPlayGroupNCompleted {
            get {
                return ResourceManager.GetString("ReadPlayGroupNCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing files while restoring playlist.
        /// </summary>
        internal static string RestoreFailedFiles {
            get {
                return ResourceManager.GetString("RestoreFailedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file failed.
        /// </summary>
        internal static string SaveFileFailed {
            get {
                return ResourceManager.GetString("SaveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SettingsButtonCancel {
            get {
                return ResourceManager.GetString("SettingsButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change color....
        /// </summary>
        internal static string SettingsButtonChangeColor {
            get {
                return ResourceManager.GetString("SettingsButtonChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SettingsButtonOK {
            get {
                return ResourceManager.GetString("SettingsButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restore defaults.
        /// </summary>
        internal static string SettingsButtonReset {
            get {
                return ResourceManager.GetString("SettingsButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 ch.
        /// </summary>
        internal static string SettingsCbItemChannelCount10 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16 ch.
        /// </summary>
        internal static string SettingsCbItemChannelCount16 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18 ch.
        /// </summary>
        internal static string SettingsCbItemChannelCount18 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 ch stereo.
        /// </summary>
        internal static string SettingsCbItemChannelCount2 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 ch.
        /// </summary>
        internal static string SettingsCbItemChannelCount24 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26 ch.
        /// </summary>
        internal static string SettingsCbItemChannelCount26 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32 ch.
        /// </summary>
        internal static string SettingsCbItemChannelCount32 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 ch.
        /// </summary>
        internal static string SettingsCbItemChannelCount4 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 ch (5.1 ch).
        /// </summary>
        internal static string SettingsCbItemChannelCount6 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 ch (7.1 ch).
        /// </summary>
        internal static string SettingsCbItemChannelCount8 {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCount8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Mix Format channel count.
        /// </summary>
        internal static string SettingsCbItemChannelCountMixFormat {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCountMixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use original channel count.
        /// </summary>
        internal static string SettingsCbItemChannelCountNotChanged {
            get {
                return ResourceManager.GetString("SettingsCbItemChannelCountNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternating row background.
        /// </summary>
        internal static string SettingsCheckBoxAlternateBackground {
            get {
                return ResourceManager.GetString("SettingsCheckBoxAlternateBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add silent channel for ch. count to be even number.
        /// </summary>
        internal static string SettingsCheckBoxChannelCountEven {
            get {
                return ResourceManager.GetString("SettingsCheckBoxChannelCountEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display cover art images.
        /// </summary>
        internal static string SettingsCheckBoxCoverart {
            get {
                return ResourceManager.GetString("SettingsCheckBoxCoverart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU rendering.
        /// </summary>
        internal static string SettingsCheckBoxGpuRendering {
            get {
                return ResourceManager.GetString("SettingsCheckBoxGpuRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call IsFormatSupported on playback.
        /// </summary>
        internal static string SettingsCheckBoxIsFormatSupportedCall {
            get {
                return ResourceManager.GetString("SettingsCheckBoxIsFormatSupportedCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Window position and size.
        /// </summary>
        internal static string SettingsCheckBoxManuallySetMainWindowDimension {
            get {
                return ResourceManager.GetString("SettingsCheckBoxManuallySetMainWindowDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallelize file read (for Solid State Drives).
        /// </summary>
        internal static string SettingsCheckBoxParallelRead {
            get {
                return ResourceManager.GetString("SettingsCheckBoxParallelRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set [Batch read endpoint] flag after INDEX00.
        /// </summary>
        internal static string SettingsCheckBoxPlaceKokomadeAterIndex00 {
            get {
                return ResourceManager.GetString("SettingsCheckBoxPlaceKokomadeAterIndex00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string SettingsCheckBoxPlayingTimeBold {
            get {
                return ResourceManager.GetString("SettingsCheckBoxPlayingTimeBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce PCM volume:.
        /// </summary>
        internal static string SettingsCheckBoxReduceVolume {
            get {
                return ResourceManager.GetString("SettingsCheckBoxReduceVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize GUI redraw when playing.
        /// </summary>
        internal static string SettingsCheckBoxRefrainRedraw {
            get {
                return ResourceManager.GetString("SettingsCheckBoxRefrainRedraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set [Batch read endpoint] on file drop.
        /// </summary>
        internal static string SettingsCheckBoxSetBatchReadEndpoint {
            get {
                return ResourceManager.GetString("SettingsCheckBoxSetBatchReadEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort dropped folder items.
        /// </summary>
        internal static string SettingsCheckboxSortDropFolder {
            get {
                return ResourceManager.GetString("SettingsCheckboxSortDropFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort dropped files.
        /// </summary>
        internal static string SettingsCheckBoxSortDroppedFiles {
            get {
                return ResourceManager.GetString("SettingsCheckBoxSortDroppedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore the playlist on program startup.
        /// </summary>
        internal static string SettingsCheckBoxStorePlaylistContent {
            get {
                return ResourceManager.GetString("SettingsCheckBoxStorePlaylistContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke timeBeginPeriod(1).
        /// </summary>
        internal static string SettingsCheckBoxTimePeriod1 {
            get {
                return ResourceManager.GetString("SettingsCheckBoxTimePeriod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify MD5 sum on FLAC file read.
        /// </summary>
        internal static string SettingsCheckBoxVerifyFlacMD5Sum {
            get {
                return ResourceManager.GetString("SettingsCheckBoxVerifyFlacMD5Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding:.
        /// </summary>
        internal static string SettingsCueEncoding {
            get {
                return ResourceManager.GetString("SettingsCueEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Count Settings.
        /// </summary>
        internal static string SettingsGroupBoxChannelCount {
            get {
                return ResourceManager.GetString("SettingsGroupBoxChannelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUE sheet settings.
        /// </summary>
        internal static string SettingsGroupBoxCuesheetSettings {
            get {
                return ResourceManager.GetString("SettingsGroupBoxCuesheetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device buffer flush settings.
        /// </summary>
        internal static string SettingsGroupBoxDeviceBufferFlush {
            get {
                return ResourceManager.GetString("SettingsGroupBoxDeviceBufferFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display settings.
        /// </summary>
        internal static string SettingsGroupBoxDisplaySettings {
            get {
                return ResourceManager.GetString("SettingsGroupBoxDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File read settings.
        /// </summary>
        internal static string SettingsGroupBoxFile {
            get {
                return ResourceManager.GetString("SettingsGroupBoxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback thread settings.
        /// </summary>
        internal static string SettingsGroupBoxPlaybackThread {
            get {
                return ResourceManager.GetString("SettingsGroupBoxPlaybackThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render thread task type.
        /// </summary>
        internal static string SettingsGroupBoxRenderThreadTaskType {
            get {
                return ResourceManager.GetString("SettingsGroupBoxRenderThreadTaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer resolution.
        /// </summary>
        internal static string SettingsGroupBoxTimerResolution {
            get {
                return ResourceManager.GetString("SettingsGroupBoxTimerResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASAPI exclusive mode settings.
        /// </summary>
        internal static string SettingsGroupBoxWasapiExclusive {
            get {
                return ResourceManager.GetString("SettingsGroupBoxWasapiExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WASAPI shared mode settings.
        /// </summary>
        internal static string SettingsGroupBoxWasapiShared {
            get {
                return ResourceManager.GetString("SettingsGroupBoxWasapiShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resampler MFT Quality (1 to 60):.
        /// </summary>
        internal static string SettingsLabelConversionQuality {
            get {
                return ResourceManager.GetString("SettingsLabelConversionQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        internal static string SettingsLabelFontPoints {
            get {
                return ResourceManager.GetString("SettingsLabelFontPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise shaping option:.
        /// </summary>
        internal static string SettingsLabelNoiseShaping {
            get {
                return ResourceManager.GetString("SettingsLabelNoiseShaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing time font:.
        /// </summary>
        internal static string SettingsLabelPlayingTimeFont {
            get {
                return ResourceManager.GetString("SettingsLabelPlayingTimeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantization bit rate to pass through the WASAPI(Converts on file loading).
        /// </summary>
        internal static string SettingsLabelQuantizationBitrate {
            get {
                return ResourceManager.GetString("SettingsLabelQuantizationBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero flush period on playback starts:.
        /// </summary>
        internal static string SettingsLabelZeroFlushSeconds {
            get {
                return ResourceManager.GetString("SettingsLabelZeroFlushSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        internal static string SettingsLabelZeroFlushUnit {
            get {
                return ResourceManager.GetString("SettingsLabelZeroFlushUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just truncate lower bits when bits per sample is reduced to 16-bit.
        /// </summary>
        internal static string SettingsNoNoiseShaping {
            get {
                return ResourceManager.GetString("SettingsNoNoiseShaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dither when bits per sample is reduced to 16-bit.
        /// </summary>
        internal static string SettingsPerformDither {
            get {
                return ResourceManager.GetString("SettingsPerformDither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform dithered noise shaping when bits per sample is reduced to 16-bit.
        /// </summary>
        internal static string SettingsPerformDitheredNoiseShaping {
            get {
                return ResourceManager.GetString("SettingsPerformDitheredNoiseShaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform noise shaping when bits per sample is reduced to 16-bit.
        /// </summary>
        internal static string SettingsPerformNoiseShaping {
            get {
                return ResourceManager.GetString("SettingsPerformNoiseShaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto select.
        /// </summary>
        internal static string SettingsRadioButtonBpsAutoSelect {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsAutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary32(IEEE754 single precision floating point format: Supported hardware is very rare).
        /// </summary>
        internal static string SettingsRadioButtonBpsSfloat32 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSfloat32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16bit integer(Truncates lower bits when 24bps or 32bps data arrives).
        /// </summary>
        internal static string SettingsRadioButtonBpsSint16 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSint16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24bit integer(Fills 0 to lower bits when 16bps data arrives, Truncates lower bits when 32bps data arrives).
        /// </summary>
        internal static string SettingsRadioButtonBpsSint24 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSint24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32bit integer(Fill 0s to lower bits, Valid bits=32bps).
        /// </summary>
        internal static string SettingsRadioButtonBpsSint32 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSint32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32bit integer, valid bits=24(Int32, Valid bits=24bps).
        /// </summary>
        internal static string SettingsRadioButtonBpsSint32V24 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSint32V24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        internal static string SettingsRadioButtonTaskAudio {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTaskAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        internal static string SettingsRadioButtonTaskNone {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTaskNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string SettingsRadioButtonTaskPlayback {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTaskPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro Audio.
        /// </summary>
        internal static string SettingsRadioButtonTaskProAudio {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTaskProAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale maximum magnitude to 0.98 to soothe limiter APO.
        /// </summary>
        internal static string SettingsSootheLimiterApo {
            get {
                return ResourceManager.GetString("SettingsSootheLimiterApo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer resolution = 1 ms.
        /// </summary>
        internal static string SettingsTimerResolution1Millisec {
            get {
                return ResourceManager.GetString("SettingsTimerResolution1Millisec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer reso=0.5 ms (unstable).
        /// </summary>
        internal static string SettingsTimerResolution500Microsec {
            get {
                return ResourceManager.GetString("SettingsTimerResolution500Microsec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default timer resolution.
        /// </summary>
        internal static string SettingsTimerResolutionDefault {
            get {
                return ResourceManager.GetString("SettingsTimerResolutionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayPcmWin detailed settings.
        /// </summary>
        internal static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please confirm sample rate or quantization bit rate are supported on your device using &quot;list supported format&quot; feature. Press [Clear the playlist][List supported format]
        ///*Some professional audio devices (RME Fireface, M-Audio ProFire, Echo AudioFire etc.) are not able to be changed master sampling rate via WASAPI. Please use FireFace settings, M-Audio ProFire control panel or equivalent tools on your system tray to change master sampling rate of those devices before playback.
        ///*44.1kHz and 88.2kHz sample  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetupFailAdvice {
            get {
                return ResourceManager.GetString("SetupFailAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files are disappeared. Playlist updated..
        /// </summary>
        internal static string SomeFilesAreDisappeared {
            get {
                return ResourceManager.GetString("SomeFilesAreDisappeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer driven.
        /// </summary>
        internal static string TimerDriven {
            get {
                return ResourceManager.GetString("TimerDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file contains Too many channels(&gt;31).
        /// </summary>
        internal static string TooManyChannels {
            get {
                return ResourceManager.GetString("TooManyChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream..
        /// </summary>
        internal static string UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using device state change detected! DeviceName={0} DeviceId={1}.
        /// </summary>
        internal static string UsingDeviceStateChanged {
            get {
                return ResourceManager.GetString("UsingDeviceStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid bits.
        /// </summary>
        internal static string ValidBits {
            get {
                return ResourceManager.GetString("ValidBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
