//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayPcmWin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayPcmWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Activated Sound Effects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioFilterActivated {
            get {
                return ResourceManager.GetString("AudioFilterActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Available Sound Effects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioFilterAvailable {
            get {
                return ResourceManager.GetString("AudioFilterAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioFilterClear {
            get {
                return ResourceManager.GetString("AudioFilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monaural mix (PCM) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioFilterMonauralMix {
            get {
                return ResourceManager.GetString("AudioFilterMonauralMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invert polarity (PCM, DoP DSD) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioFilterPolarityInvert {
            get {
                return ResourceManager.GetString("AudioFilterPolarityInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonSoundEffectsSettings {
            get {
                return ResourceManager.GetString("ButtonSoundEffectsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorry... Please stop playback to add files to the playlist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotAddFile {
            get {
                return ResourceManager.GetString("CannotAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable DSP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckBoxSoundEffects {
            get {
                return ResourceManager.GetString("CheckBoxSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipped sample value detected on floating point PCM data!
        ///  Clipped sample value count={1}, FileName={0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClippedSampleDetected {
            get {
                return ResourceManager.GetString("ClippedSampleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeviceStateChanged. DeviceId={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceStateChanged {
            get {
                return ResourceManager.GetString("DeviceStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some kind of data is dropped but the data is not file nor folder. Failed to process dropped items. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DroppedDataIsNotFile {
            get {
                return ResourceManager.GetString("DroppedDataIsNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter file version number mismatch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorFilterFileVersionMismatch {
            get {
                return ResourceManager.GetString("ErrorFilterFileVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event driven に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EventDriven {
            get {
                return ResourceManager.GetString("EventDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exclusive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CUE files|*.CUE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterCueFiles {
            get {
                return ResourceManager.GetString("FilterCueFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M3U files|*.M3U;*.M3U8 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterM3uFiles {
            get {
                return ResourceManager.GetString("FilterM3uFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PPWPL files|*.PPWPL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterPpwplFiles {
            get {
                return ResourceManager.GetString("FilterPpwplFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported files|*.WAV;*.WAVE;*.FLAC;*.AIF;*.AIFF;*.AIFC;*.AIFFC;*.DSF;*.DFF;*.CUE;*.PPWPL;*.M3U;*.M3U8|WAVE files|*.WAV;*.WAVE|FLAC files|*.FLAC|AIFF files|*.AIF;*.AIFF;*.AIFC;*AIFFC|DSF files|*.DSF|DFF files|*.DFF|CUE files|*.CUE|PPWPL files|*.PPWPL|M3U files|*.M3U;*.M3U8|All files|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterSupportedFiles {
            get {
                return ResourceManager.GetString("FilterSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Float に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FloatingPointNumbers {
            get {
                return ResourceManager.GetString("FloatingPointNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sound Effects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GroupBoxSoundEffects {
            get {
                return ResourceManager.GetString("GroupBoxSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copyright (C)  2010 yamamoto2002
        ///
        ///■Special Thanks■
        ///Simplified-chinese localization: Tsong Zhang
        ///
        ///PlayPcmWin uses libFLAC.
        ///libFLAC license is a New BSD License. libFlacLicense.txt on the PlayPcmWin.exe folder contains full text of license.
        ///
        ///PlayPcmWin uses Jcode.pm character encoding detect function.
        ///Jcode.pm copyright is as follows: Copyright 1999-2005 Dan Kogai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Clear the playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonClearPlayList {
            get {
                return ResourceManager.GetString("MainButtonClearPlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delist the selected file(_R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonDelistSelected {
            get {
                return ResourceManager.GetString("MainButtonDelistSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   L_ist supported formats に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonInspectDevice {
            get {
                return ResourceManager.GetString("MainButtonInspectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonNext {
            get {
                return ResourceManager.GetString("MainButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pa_use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonPause {
            get {
                return ResourceManager.GetString("MainButtonPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonPlay {
            get {
                return ResourceManager.GetString("MainButtonPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prev に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonPrev {
            get {
                return ResourceManager.GetString("MainButtonPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume(_U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonResume {
            get {
                return ResourceManager.GetString("MainButtonResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Detailed settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonSettings {
            get {
                return ResourceManager.GetString("MainButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainButtonStop {
            get {
                return ResourceManager.GetString("MainButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Clear the playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainCMenuPlaylistClear {
            get {
                return ResourceManager.GetString("MainCMenuPlaylistClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist item edit mode(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainCMenuPlayListEditMode {
            get {
                return ResourceManager.GetString("MainCMenuPlayListEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Album name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnAlbumTitle {
            get {
                return ResourceManager.GetString("MainDataGridColumnAlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Artists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnArtist {
            get {
                return ResourceManager.GetString("MainDataGridColumnArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitrate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnBitRate {
            get {
                return ResourceManager.GetString("MainDataGridColumnBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnDuration {
            get {
                return ResourceManager.GetString("MainDataGridColumnDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnIndexNr {
            get {
                return ResourceManager.GetString("MainDataGridColumnIndexNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number of channels に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnNumChannels {
            get {
                return ResourceManager.GetString("MainDataGridColumnNumChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quantization bit rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnQuantizationBitRate {
            get {
                return ResourceManager.GetString("MainDataGridColumnQuantizationBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch read endpoint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnReadSeparaterAfter {
            get {
                return ResourceManager.GetString("MainDataGridColumnReadSeparaterAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample rate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnSampleRate {
            get {
                return ResourceManager.GetString("MainDataGridColumnSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainDataGridColumnTitle {
            get {
                return ResourceManager.GetString("MainDataGridColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainExpanderSettings {
            get {
                return ResourceManager.GetString("MainExpanderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainGroupBoxLog {
            get {
                return ResourceManager.GetString("MainGroupBoxLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainGroupBoxOutputDevices {
            get {
                return ResourceManager.GetString("MainGroupBoxOutputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playback control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainGroupBoxPlaybackControl {
            get {
                return ResourceManager.GetString("MainGroupBoxPlaybackControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist(Drop audio files from Explorer to add files) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainGroupBoxPlaylist {
            get {
                return ResourceManager.GetString("MainGroupBoxPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data feed mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainGroupBoxWasapiDataFeedMode {
            get {
                return ResourceManager.GetString("MainGroupBoxWasapiDataFeedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainGroupBoxWasapiOperationMode {
            get {
                return ResourceManager.GetString("MainGroupBoxWasapiOperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output latency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainGroupBoxWasapiOutputLatency {
            get {
                return ResourceManager.GetString("MainGroupBoxWasapiOutputLatency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WASAPI settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainGroupBoxWasapiSettings {
            get {
                return ResourceManager.GetString("MainGroupBoxWasapiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All tracks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPlayModeAllTracks {
            get {
                return ResourceManager.GetString("MainPlayModeAllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All tracks repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPlayModeAllTracksRepeat {
            get {
                return ResourceManager.GetString("MainPlayModeAllTracksRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One track に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPlayModeOneTrack {
            get {
                return ResourceManager.GetString("MainPlayModeOneTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One track repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPlayModeOneTrackRepeat {
            get {
                return ResourceManager.GetString("MainPlayModeOneTrackRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPlayModeShuffle {
            get {
                return ResourceManager.GetString("MainPlayModeShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPlayModeShuffleRepeat {
            get {
                return ResourceManager.GetString("MainPlayModeShuffleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event driven に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainRadioButtonEventDriven {
            get {
                return ResourceManager.GetString("MainRadioButtonEventDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exclusive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainRadioButtonExclusive {
            get {
                return ResourceManager.GetString("MainRadioButtonExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shared に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainRadioButtonShared {
            get {
                return ResourceManager.GetString("MainRadioButtonShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer driven に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainRadioButtonTimerDriven {
            get {
                return ResourceManager.GetString("MainRadioButtonTimerDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading files... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainStatusChangingPlayGroup {
            get {
                return ResourceManager.GetString("MainStatusChangingPlayGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainStatusPaused {
            get {
                return ResourceManager.GetString("MainStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainStatusPlaying {
            get {
                return ResourceManager.GetString("MainStatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please create the playlist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainStatusPleaseCreatePlaylist {
            get {
                return ResourceManager.GetString("MainStatusPleaseCreatePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add more files to the playlist or Press play button に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainStatusPressPlayButton {
            get {
                return ResourceManager.GetString("MainStatusPressPlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read completed. ready to play. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainStatusReadCompleted {
            get {
                return ResourceManager.GetString("MainStatusReadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup device completed. Now reading files to main memory... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainStatusReadingFiles {
            get {
                return ResourceManager.GetString("MainStatusReadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading playlist... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainStatusReadingPlaylist {
            get {
                return ResourceManager.GetString("MainStatusReadingPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopping... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainStatusStopping {
            get {
                return ResourceManager.GetString("MainStatusStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MD5 sum validation failed! File may be corrupted: {0}
        ///  MD5 in metadata    = {1}
        ///  MD5 from PCM data= {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MD5SumMismatch {
            get {
                return ResourceManager.GetString("MD5SumMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File does not have STREAMINFO MD5 signature. Could not perform MD5 validation: {0}
        ///  MD5 from PCM data= {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MD5SumNotAvailable {
            get {
                return ResourceManager.GetString("MD5SumNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MD5sum validation succeeded. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MD5SumValid {
            get {
                return ResourceManager.GetString("MD5SumValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory exhausted. Please reduce files on playlist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MemoryExhausted {
            get {
                return ResourceManager.GetString("MemoryExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFileExit {
            get {
                return ResourceManager.GetString("MenuItemFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear the playlist(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFileNew {
            get {
                return ResourceManager.GetString("MenuItemFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFileOpen {
            get {
                return ResourceManager.GetString("MenuItemFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save _As... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFileSaveAs {
            get {
                return ResourceManager.GetString("MenuItemFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the playlist as a _CUE sheet... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemFileSaveCueAs {
            get {
                return ResourceManager.GetString("MenuItemFileSaveCueAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemHelpAbout {
            get {
                return ResourceManager.GetString("MenuItemHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visit PlayPcmWin _Website に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemHelpWeb {
            get {
                return ResourceManager.GetString("MenuItemHelpWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Clear the playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemPlayListClear {
            get {
                return ResourceManager.GetString("MenuItemPlayListClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playlist item edit mode(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemPlayListItemEditMode {
            get {
                return ResourceManager.GetString("MenuItemPlayListItemEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuItemToolSettings {
            get {
                return ResourceManager.GetString("MenuItemToolSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   P_laylist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuPlayList {
            get {
                return ResourceManager.GetString("MenuPlayList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Tools に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing to store  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NothingToStore {
            get {
                return ResourceManager.GetString("NothingToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not supported file format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotSupportedFileFormat {
            get {
                return ResourceManager.GetString("NotSupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not supported quantization bit rate. supported formats are 16, 24 and 32 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotSupportedQuantizationBitRate {
            get {
                return ResourceManager.GetString("NotSupportedQuantizationBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play completed. elapsed time is に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayCompletedElapsedTimeIs {
            get {
                return ResourceManager.GetString("PlayCompletedElapsedTimeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play start failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayStartFailed {
            get {
                return ResourceManager.GetString("PlayStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read failed files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadFailedFiles {
            get {
                return ResourceManager.GetString("ReadFailedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read {0} file failed  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadFileFailed {
            get {
                return ResourceManager.GetString("ReadFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read playgroup {0} completed. Elapsed time: {1}ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadPlayGroupNCompleted {
            get {
                return ResourceManager.GetString("ReadPlayGroupNCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing files while restoring playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestoreFailedFiles {
            get {
                return ResourceManager.GetString("RestoreFailedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save file failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileFailed {
            get {
                return ResourceManager.GetString("SaveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsButtonCancel {
            get {
                return ResourceManager.GetString("SettingsButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change color... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsButtonChangeColor {
            get {
                return ResourceManager.GetString("SettingsButtonChangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsButtonOK {
            get {
                return ResourceManager.GetString("SettingsButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Restore defaults に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsButtonReset {
            get {
                return ResourceManager.GetString("SettingsButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alternating row background に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxAlternateBackground {
            get {
                return ResourceManager.GetString("SettingsCheckBoxAlternateBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display cover art images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxCoverart {
            get {
                return ResourceManager.GetString("SettingsCheckBoxCoverart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPU rendering に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxGpuRendering {
            get {
                return ResourceManager.GetString("SettingsCheckBoxGpuRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember Window position and size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxManuallySetMainWindowDimension {
            get {
                return ResourceManager.GetString("SettingsCheckBoxManuallySetMainWindowDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parallelize file read に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxParallelRead {
            get {
                return ResourceManager.GetString("SettingsCheckBoxParallelRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set [Batch read endpoint] flag after INDEX00 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxPlaceKokomadeAterIndex00 {
            get {
                return ResourceManager.GetString("SettingsCheckBoxPlaceKokomadeAterIndex00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bold に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxPlayingTimeBold {
            get {
                return ResourceManager.GetString("SettingsCheckBoxPlayingTimeBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize GUI redraw when playing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxRefrainRedraw {
            get {
                return ResourceManager.GetString("SettingsCheckBoxRefrainRedraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set [Batch read endpoint] on file drop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxSetBatchReadEndpoint {
            get {
                return ResourceManager.GetString("SettingsCheckBoxSetBatchReadEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort dropped folder items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckboxSortDropFolder {
            get {
                return ResourceManager.GetString("SettingsCheckboxSortDropFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort dropped files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxSortDroppedFiles {
            get {
                return ResourceManager.GetString("SettingsCheckBoxSortDroppedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Restore the playlist on program startup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxStorePlaylistContent {
            get {
                return ResourceManager.GetString("SettingsCheckBoxStorePlaylistContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invoke timeBeginPeriod(1) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxTimePeriod1 {
            get {
                return ResourceManager.GetString("SettingsCheckBoxTimePeriod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verify MD5 sum on FLAC file read に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCheckBoxVerifyFlacMD5Sum {
            get {
                return ResourceManager.GetString("SettingsCheckBoxVerifyFlacMD5Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encoding: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsCueEncoding {
            get {
                return ResourceManager.GetString("SettingsCueEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CUE sheet settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsGroupBoxCuesheetSettings {
            get {
                return ResourceManager.GetString("SettingsGroupBoxCuesheetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device buffer flush settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsGroupBoxDeviceBufferFlush {
            get {
                return ResourceManager.GetString("SettingsGroupBoxDeviceBufferFlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsGroupBoxDisplaySettings {
            get {
                return ResourceManager.GetString("SettingsGroupBoxDisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File read settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsGroupBoxFile {
            get {
                return ResourceManager.GetString("SettingsGroupBoxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playback thread settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsGroupBoxPlaybackThread {
            get {
                return ResourceManager.GetString("SettingsGroupBoxPlaybackThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Render thread task type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsGroupBoxRenderThreadTaskType {
            get {
                return ResourceManager.GetString("SettingsGroupBoxRenderThreadTaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer resolution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsGroupBoxTimerResolution {
            get {
                return ResourceManager.GetString("SettingsGroupBoxTimerResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WASAPI exclusive mode settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsGroupBoxWasapiExclusive {
            get {
                return ResourceManager.GetString("SettingsGroupBoxWasapiExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WASAPI shared mode settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsGroupBoxWasapiShared {
            get {
                return ResourceManager.GetString("SettingsGroupBoxWasapiShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resampler MFT Quality (1 to 60): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsLabelConversionQuality {
            get {
                return ResourceManager.GetString("SettingsLabelConversionQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsLabelFontPoints {
            get {
                return ResourceManager.GetString("SettingsLabelFontPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Noise shaping option: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsLabelNoiseShaping {
            get {
                return ResourceManager.GetString("SettingsLabelNoiseShaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing time font: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsLabelPlayingTimeFont {
            get {
                return ResourceManager.GetString("SettingsLabelPlayingTimeFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quantization bit rate to pass through the WASAPI(Converts on file loading) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsLabelQuantizationBitrate {
            get {
                return ResourceManager.GetString("SettingsLabelQuantizationBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zero flush period on playback starts: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsLabelZeroFlushSeconds {
            get {
                return ResourceManager.GetString("SettingsLabelZeroFlushSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsLabelZeroFlushUnit {
            get {
                return ResourceManager.GetString("SettingsLabelZeroFlushUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just truncate lower bits when bits per sample is reduced to 16-bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsNoNoiseShaping {
            get {
                return ResourceManager.GetString("SettingsNoNoiseShaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add dither when bits per sample is reduced to 16-bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPerformDither {
            get {
                return ResourceManager.GetString("SettingsPerformDither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perform dithered noise shaping when bits per sample is reduced to 16-bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPerformDitheredNoiseShaping {
            get {
                return ResourceManager.GetString("SettingsPerformDitheredNoiseShaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Perform noise shaping when bits per sample is reduced to 16-bit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPerformNoiseShaping {
            get {
                return ResourceManager.GetString("SettingsPerformNoiseShaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonBpsAutoSelect {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsAutoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binary32(IEEE754 single precision floating point format: Supported hardware is very rare) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonBpsSfloat32 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSfloat32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   16bit integer(Truncates lower bits when 24bps or 32bps data arrives) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonBpsSint16 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSint16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   24bit integer(Fills 0 to lower bits when 16bps data arrives, Truncates lower bits when 32bps data arrives) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonBpsSint24 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSint24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32bit integer(Fill 0s to lower bits, Valid bits=32bps) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonBpsSint32 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSint32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   32bit integer, valid bits=24(Int32, Valid bits=24bps) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonBpsSint32V24 {
            get {
                return ResourceManager.GetString("SettingsRadioButtonBpsSint32V24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonTaskAudio {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTaskAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playback に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonTaskNone {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTaskNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonTaskPlayback {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTaskPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pro Audio に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsRadioButtonTaskProAudio {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTaskProAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scale maximum magnitude to 0.98 to soothe limiter APO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsSootheLimiterApo {
            get {
                return ResourceManager.GetString("SettingsSootheLimiterApo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer resolution = 1 ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsTimerResolution1Millisec {
            get {
                return ResourceManager.GetString("SettingsTimerResolution1Millisec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer reso=0.5 ms (unstable) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsTimerResolution500Microsec {
            get {
                return ResourceManager.GetString("SettingsTimerResolution500Microsec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default timer resolution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsTimerResolutionDefault {
            get {
                return ResourceManager.GetString("SettingsTimerResolutionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PlayPcmWin detailed settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Please confirm sample rate or quantization bit rate are supported on your device using &quot;list supported format&quot; feature. Press [Clear the playlist][List supported format]
        ///*Some professional audio devices (RME Fireface, M-Audio ProFire, Echo AudioFire etc.) are not able to be changed master sampling rate via WASAPI. Please use FireFace settings, M-Audio ProFire control panel or equivalent tools on your system tray to change master sampling rate of those devices before playback.
        ///*44.1kHz and 88.2kHz sample  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetupFailAdvice {
            get {
                return ResourceManager.GetString("SetupFailAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shared に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer driven に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimerDriven {
            get {
                return ResourceManager.GetString("TimerDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file contains Too many channels(&gt;31) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooManyChannels {
            get {
                return ResourceManager.GetString("TooManyChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected end of stream. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using device state change detected! DeviceName={0} DeviceId={1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UsingDeviceStateChanged {
            get {
                return ResourceManager.GetString("UsingDeviceStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valid bits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidBits {
            get {
                return ResourceManager.GetString("ValidBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
