//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.4016
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WavInvert.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WavInvert.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Read wav file failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadWavFileFailed {
            get {
                return ResourceManager.GetString("ReadWavFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read wav file started: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadWavFileStarted {
            get {
                return ResourceManager.GetString("ReadWavFileStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read wav file succeeded: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadWavFileSucceeded {
            get {
                return ResourceManager.GetString("ReadWavFileSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Started に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WAV files (*.wav)|*.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WavFileFilter {
            get {
                return ResourceManager.GetString("WavFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write wav file failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteWavFileFailed {
            get {
                return ResourceManager.GetString("WriteWavFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write wav file started: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteWavFileStarted {
            get {
                return ResourceManager.GetString("WriteWavFileStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write wav file succeeded: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteWavFileSucceeded {
            get {
                return ResourceManager.GetString("WriteWavFileSucceeded", resourceCulture);
            }
        }
    }
}
