//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWShowUSBDeviceTree.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WWShowUSBDeviceTree.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Powered.
        /// </summary>
        internal static string BusPowered {
            get {
                return ResourceManager.GetString("BusPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host means PC. Device means USB device.
        ///
        ///LowSpeed : 0.19MB/s signaling bit rate, Half duplex. Yellow Colored Curve.
        ///FullSpeed : 1.5MB/s signaling bit rate, Half duplex. Yellow Colored Curve.
        ///HighSpeed : 60MB/s signaling bit rate, Half duplex. White Colored Curve.
        ///SuperSpeed : 625MB/s signaling bit rate, Full duplex. Cyan Colored Curve.
        ///SuperSpeed+ : 1.25GB/s or 2.5GB/s(USB3.2 Gen2x2) signaling bit rate, Full duplex. Magenta Colored Curve.
        ///
        ///USB1.x supports LowSpeed and FullSpeed. Yellow Colored Borde [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Powered.
        /// </summary>
        internal static string SelfPowered {
            get {
                return ResourceManager.GetString("SelfPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Description.
        /// </summary>
        internal static string ShowDesc {
            get {
                return ResourceManager.GetString("ShowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Detail.
        /// </summary>
        internal static string ShowDetail {
            get {
                return ResourceManager.GetString("ShowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream input for Playback.
        /// </summary>
        internal static string StreamForPlayback {
            get {
                return ResourceManager.GetString("StreamForPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream output for Recording.
        /// </summary>
        internal static string StreamForRecording {
            get {
                return ResourceManager.GetString("StreamForRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive.
        /// </summary>
        internal static string UAAdaptive {
            get {
                return ResourceManager.GetString("UAAdaptive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous.
        /// </summary>
        internal static string UAAsynchronous {
            get {
                return ResourceManager.GetString("UAAsynchronous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Selector.
        /// </summary>
        internal static string UAClockSelector {
            get {
                return ResourceManager.GetString("UAClockSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Source.
        /// </summary>
        internal static string UAClockSource {
            get {
                return ResourceManager.GetString("UAClockSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string UAFeedback {
            get {
                return ResourceManager.GetString("UAFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input (Device→Host) Endpoint.
        /// </summary>
        internal static string UAInputEndpoint {
            get {
                return ResourceManager.GetString("UAInputEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Terminal.
        /// </summary>
        internal static string UAInputTerminal {
            get {
                return ResourceManager.GetString("UAInputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output (Host→Device) Endpoint.
        /// </summary>
        internal static string UAOutputEndpoint {
            get {
                return ResourceManager.GetString("UAOutputEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Terminal.
        /// </summary>
        internal static string UAOutputTerminal {
            get {
                return ResourceManager.GetString("UAOutputTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronous.
        /// </summary>
        internal static string UASynchronous {
            get {
                return ResourceManager.GetString("UASynchronous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Audio Class.
        /// </summary>
        internal static string UsbAudioClass {
            get {
                return ResourceManager.GetString("UsbAudioClass", resourceCulture);
            }
        }
    }
}
