//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3074
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wav2Gnuplot.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wav2Gnuplot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Main window may be occulted by this console window... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConsoleIntroduction {
            get {
                return ResourceManager.GetString("ConsoleIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read WAV file:{0}, Write Gnuplot data file: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileSpecified {
            get {
                return ResourceManager.GetString("FileSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gnuplot sample files (*.dat)|*.dat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GnuplotFileFilter {
            get {
                return ResourceManager.GetString("GnuplotFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please specify wave file pathes to input. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process started. {0} ==&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessStarted {
            get {
                return ResourceManager.GetString("ProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   read failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadFileFailFormat {
            get {
                return ResourceManager.GetString("ReadFileFailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read file: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadFileStarted {
            get {
                return ResourceManager.GetString("ReadFileStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read wav file failed: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadWavFileFailed {
            get {
                return ResourceManager.GetString("ReadWavFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WAV files (*.wav)|*.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WavFileFilter {
            get {
                return ResourceManager.GetString("WavFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   this file has {0} samples. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WavFileSummary {
            get {
                return ResourceManager.GetString("WavFileSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WAV file is too short must be longer than {1} seconds: this file has {2} samples. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WavFileTooShort {
            get {
                return ResourceManager.GetString("WavFileTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write failed. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteFailed {
            get {
                return ResourceManager.GetString("WriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write succeeded. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteSucceeded {
            get {
                return ResourceManager.GetString("WriteSucceeded", resourceCulture);
            }
        }
    }
}
