//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWAudioFilter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WWAudioFilter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new filter.
        /// </summary>
        internal static string ButtonAddNewFilter {
            get {
                return ResourceManager.GetString("ButtonAddNewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Browse....
        /// </summary>
        internal static string ButtonBrowseB {
            get {
                return ResourceManager.GetString("ButtonBrowseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B_rowse....
        /// </summary>
        internal static string ButtonBrowseR {
            get {
                return ResourceManager.GetString("ButtonBrowseR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        internal static string ButtonDeleteSelected {
            get {
                return ResourceManager.GetString("ButtonDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected.
        /// </summary>
        internal static string ButtonEditSelected {
            get {
                return ResourceManager.GetString("ButtonEditSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load settings....
        /// </summary>
        internal static string ButtonLoadSettings {
            get {
                return ResourceManager.GetString("ButtonLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down selected.
        /// </summary>
        internal static string ButtonMoveDownSelected {
            get {
                return ResourceManager.GetString("ButtonMoveDownSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up selected.
        /// </summary>
        internal static string ButtonMoveUpSelected {
            get {
                return ResourceManager.GetString("ButtonMoveUpSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings as....
        /// </summary>
        internal static string ButtonSaveSettingsAs {
            get {
                return ResourceManager.GetString("ButtonSaveSettingsAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start conversion.
        /// </summary>
        internal static string ButtonStartConversion {
            get {
                return ResourceManager.GetString("ButtonStartConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this filter.
        /// </summary>
        internal static string ButtonUseThisFilter {
            get {
                return ResourceManager.GetString("ButtonUseThisFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Hermite Spline upsampler.
        /// </summary>
        internal static string CbIteCubicHermiteSplineUpsampler {
            get {
                return ResourceManager.GetString("CbIteCubicHermiteSplineUpsampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single stage CIC.
        /// </summary>
        internal static string CbItemCicTypeSingleStage {
            get {
                return ResourceManager.GetString("CbItemCicTypeSingleStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick 1st sample from incoming two samples.
        /// </summary>
        internal static string CbItemDownsamplerOption0 {
            get {
                return ResourceManager.GetString("CbItemDownsamplerOption0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pick 2nd sample from incoming two samples.
        /// </summary>
        internal static string CbItemDownsamplerOption1 {
            get {
                return ResourceManager.GetString("CbItemDownsamplerOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x.
        /// </summary>
        internal static string CbItemDownsamplerType2x {
            get {
                return ResourceManager.GetString("CbItemDownsamplerType2x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT Upsampler.
        /// </summary>
        internal static string CbItemFftUpsampler {
            get {
                return ResourceManager.GetString("CbItemFftUpsampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Zeroes Upsampler.
        /// </summary>
        internal static string CbItemInsertZeroesUpsampler {
            get {
                return ResourceManager.GetString("CbItemInsertZeroesUpsampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear interpolation Upsampler.
        /// </summary>
        internal static string CbItemLineDrawUpsampler {
            get {
                return ResourceManager.GetString("CbItemLineDrawUpsampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd order.
        /// </summary>
        internal static string CbItemNoiseShaping2nd {
            get {
                return ResourceManager.GetString("CbItemNoiseShaping2nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th order.
        /// </summary>
        internal static string CbItemNoiseShaping4th {
            get {
                return ResourceManager.GetString("CbItemNoiseShaping4th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero-Order Hold Upsampler.
        /// </summary>
        internal static string CbItemZohUpsampler {
            get {
                return ResourceManager.GetString("CbItemZohUpsampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt.
        /// </summary>
        internal static string CrossfeedDefaultExt {
            get {
                return ResourceManager.GetString("CrossfeedDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossfeed Filter|*.cfeed.
        /// </summary>
        internal static string CrossfeedFileFilter {
            get {
                return ResourceManager.GetString("CrossfeedFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropped data is not file.
        /// </summary>
        internal static string DroppedDataIsNotFile {
            get {
                return ResourceManager.GetString("DroppedDataIsNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Cic delay value in larger than 1 integer.
        /// </summary>
        internal static string ErrorCicDelay {
            get {
                return ResourceManager.GetString("ErrorCicDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify crossfeed Filter file.
        /// </summary>
        internal static string ErrorCrossfeedFile {
            get {
                return ResourceManager.GetString("ErrorCrossfeedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Dynamic range scaling lsb scaling value parse error.
        /// </summary>
        internal static string ErrorDynamicRangeCompressionLsbScaling {
            get {
                return ResourceManager.GetString("ErrorDynamicRangeCompressionLsbScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add one or more filters.
        /// </summary>
        internal static string ErrorFilterEmpty {
            get {
                return ResourceManager.GetString("ErrorFilterEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter file version mismatch. expected version={0}, file version={1}.
        /// </summary>
        internal static string ErrorFilterFileVersionMismatch {
            get {
                return ResourceManager.GetString("ErrorFilterFileVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error First order all-pass IIR a parameter.
        /// </summary>
        internal static string ErrorFirstOrderAllPassIIR {
            get {
                return ResourceManager.GetString("ErrorFirstOrderAllPassIIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input fundamentals gain in number.
        /// </summary>
        internal static string ErrorFundamentalsGainValue {
            get {
                return ResourceManager.GetString("ErrorFundamentalsGainValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input gain value in number.
        /// </summary>
        internal static string ErrorGainValueIsNan {
            get {
                return ResourceManager.GetString("ErrorGainValueIsNan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input gain value larger than 0.0.
        /// </summary>
        internal static string ErrorGainValueIsTooSmall {
            get {
                return ResourceManager.GetString("ErrorGainValueIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaussian noise level parse error..
        /// </summary>
        internal static string ErrorGaussianNoiseLevel {
            get {
                return ResourceManager.GetString("ErrorGaussianNoiseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Filter taps value N where N+1 equals power of 4.
        /// </summary>
        internal static string ErrorHalfbandTaps {
            get {
                return ResourceManager.GetString("ErrorHalfbandTaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Low pass filter cutoff frequency in number.
        /// </summary>
        internal static string ErrorLpfCutoffFreqIsNan {
            get {
                return ResourceManager.GetString("ErrorLpfCutoffFreqIsNan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Low pass filter cutoff frequency larger than 0.0.
        /// </summary>
        internal static string ErrorLpfCutoffFreqIsNegative {
            get {
                return ResourceManager.GetString("ErrorLpfCutoffFreqIsNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Low pass filter slope in number.
        /// </summary>
        internal static string ErrorLpfSlopeIsNan {
            get {
                return ResourceManager.GetString("ErrorLpfSlopeIsNan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Low pass filter slope larger than 1.
        /// </summary>
        internal static string ErrorLpfSlopeIsTooSmall {
            get {
                return ResourceManager.GetString("ErrorLpfSlopeIsTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prease input Target Quantization Bit Rate in number.
        /// </summary>
        internal static string ErrorNoiseShapingBitIsNan {
            get {
                return ResourceManager.GetString("ErrorNoiseShapingBitIsNan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prease input Target Quantization Bit Rate in integer in the range of 1 to 23.
        /// </summary>
        internal static string ErrorNoiseShapingBitIsOutOfRange {
            get {
                return ResourceManager.GetString("ErrorNoiseShapingBitIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error normalize amplutude value must be number equals to or less than 0.0.
        /// </summary>
        internal static string ErrorNormalizeValue {
            get {
                return ResourceManager.GetString("ErrorNormalizeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output data becomes too large! {0} Gbytes.
        /// </summary>
        internal static string ErrorOutputDataTooLarge {
            get {
                return ResourceManager.GetString("ErrorOutputDataTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPDF Jitter Amount must be 0 or larger value.
        /// </summary>
        internal static string ErrorRpdfJitterAmount {
            get {
                return ResourceManager.GetString("ErrorRpdfJitterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too large magnitude sample detected! channel={0}, magnitude={1:0.000}
        ///.
        /// </summary>
        internal static string ErrorSampleValueClipped {
            get {
                return ResourceManager.GetString("ErrorSampleValueClipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Second order all-pass IIR r parameter.
        /// </summary>
        internal static string ErrorSecondOrderAllPassIirR {
            get {
                return ResourceManager.GetString("ErrorSecondOrderAllPassIirR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Second order all-pass IIR θ parameter.
        /// </summary>
        internal static string ErrorSecondOrderAllPassIirT {
            get {
                return ResourceManager.GetString("ErrorSecondOrderAllPassIirT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinusoidal Jitter Amount must be 0 or larger value.
        /// </summary>
        internal static string ErrorSinusolidalJitterAmount {
            get {
                return ResourceManager.GetString("ErrorSinusolidalJitterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinusoidal Jitter Freq must be 0 or larger value.
        /// </summary>
        internal static string ErrorSinusolidalJitterFreq {
            get {
                return ResourceManager.GetString("ErrorSinusolidalJitterFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: target bit depth b must number in the range:  1 ≤ b ≤ 23.
        /// </summary>
        internal static string ErrorTargetBitDepth {
            get {
                return ResourceManager.GetString("ErrorTargetBitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPDF Jitter Amount must be 0 or larger value.
        /// </summary>
        internal static string ErrorTpdfJitterAmount {
            get {
                return ResourceManager.GetString("ErrorTpdfJitterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error uneven bit dac unevenness value parse error.
        /// </summary>
        internal static string ErrorUnevenBitDacLsbScaling {
            get {
                return ResourceManager.GetString("ErrorUnevenBitDacLsbScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify different file to write. WWAudioFilter cannot write to input file..
        /// </summary>
        internal static string ErrorWriteToReadFile {
            get {
                return ResourceManager.GetString("ErrorWriteToReadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add octave bass unison of the sound below 80Hz: Gain={0:0.00}dB.
        /// </summary>
        internal static string FilterAddFundamentalsDesc {
            get {
                return ResourceManager.GetString("FilterAddFundamentalsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIC Filter: {0}, Comb delay={1}.
        /// </summary>
        internal static string FilterCicFilterDesc {
            get {
                return ResourceManager.GetString("FilterCicFilterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crossfeed: ConfigFile={0}.
        /// </summary>
        internal static string FilterCrossfeedDesc {
            get {
                return ResourceManager.GetString("FilterCrossfeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic Hermite Spline upsample: {0}x.
        /// </summary>
        internal static string FilterCubicHermiteSplineDesc {
            get {
                return ResourceManager.GetString("FilterCubicHermiteSplineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downsample: {0}x, pick {1} th sample.
        /// </summary>
        internal static string FilterDownsamplerDesc {
            get {
                return ResourceManager.GetString("FilterDownsamplerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic range compression: 24bit LSB gain= {0} dB.
        /// </summary>
        internal static string FilterDynamicRangeCompressionDesc {
            get {
                return ResourceManager.GetString("FilterDynamicRangeCompressionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT upsample: {0}x, FFT length={1}, Overlap={2}.
        /// </summary>
        internal static string FilterFftUpsampleDesc {
            get {
                return ResourceManager.GetString("FilterFftUpsampleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Order All-pass IIR Filter: a={0}.
        /// </summary>
        internal static string FilterFirstOrderAllPassIIRDesc {
            get {
                return ResourceManager.GetString("FilterFirstOrderAllPassIIRDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC files|*.flac.
        /// </summary>
        internal static string FilterFlacFiles {
            get {
                return ResourceManager.GetString("FilterFlacFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain : {0}x ({1:0.00}dB).
        /// </summary>
        internal static string FilterGainDesc {
            get {
                return ResourceManager.GetString("FilterGainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-band Filter: taps={0}.
        /// </summary>
        internal static string FilterHalfbandDesc {
            get {
                return ResourceManager.GetString("FilterHalfbandDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Zeroes Upsampler: {0}x.
        /// </summary>
        internal static string FilterInsertZeroesDesc {
            get {
                return ResourceManager.GetString("FilterInsertZeroesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Jitter : Sinusoidal={0}Hz {1}ns, TPDF={2}ns,  RPDF={3}ns, Filter Length={4}.
        /// </summary>
        internal static string FilterJitterAddDesc {
            get {
                return ResourceManager.GetString("FilterJitterAddDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear inerpolation upsample: {0}x.
        /// </summary>
        internal static string FilterLineDrawDesc {
            get {
                return ResourceManager.GetString("FilterLineDrawDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LPF : Cutoff={0}Hz, slope={1}db/oct, FIR length={2}.
        /// </summary>
        internal static string FilterLpfDesc {
            get {
                return ResourceManager.GetString("FilterLpfDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd order MASH noise shaping: targetBitsPerSample={0}.
        /// </summary>
        internal static string FilterMashDesc {
            get {
                return ResourceManager.GetString("FilterMashDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4th order noise shaping: targetBitsPerSample={0}.
        /// </summary>
        internal static string FilterNoiseShaping4thDesc {
            get {
                return ResourceManager.GetString("FilterNoiseShaping4thDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise shaping: order={0}, targetBitsPerSample={1}.
        /// </summary>
        internal static string FilterNoiseShapingDesc {
            get {
                return ResourceManager.GetString("FilterNoiseShapingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize signal level max={0}dBFS.
        /// </summary>
        internal static string FilterNormalizeDesc {
            get {
                return ResourceManager.GetString("FilterNormalizeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files(*.wav, *.flac)|*.wav;*.flac.
        /// </summary>
        internal static string FilterPcmFiles {
            get {
                return ResourceManager.GetString("FilterPcmFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce bit depth to {0} bit.
        /// </summary>
        internal static string FilterReduceBitDepthDesc {
            get {
                return ResourceManager.GetString("FilterReduceBitDepthDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Order All-pass IIR Filter: r={0}, θ={1}°.
        /// </summary>
        internal static string FilterSecondOrderAllPassIIRDesc {
            get {
                return ResourceManager.GetString("FilterSecondOrderAllPassIIRDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tag : {0} = &quot;{1}&quot;.
        /// </summary>
        internal static string FilterTagEdit {
            get {
                return ResourceManager.GetString("FilterTagEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uneven bit DAC simulation. 16bit LSB unevenness +{0} dB.
        /// </summary>
        internal static string FilterUnevenBitDacDesc {
            get {
                return ResourceManager.GetString("FilterUnevenBitDacDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLAC files|*.flac|DSF files|*.dsf.
        /// </summary>
        internal static string FilterWriteAudioFiles {
            get {
                return ResourceManager.GetString("FilterWriteAudioFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWAudioFilter files|*.wwaf.
        /// </summary>
        internal static string FilterWWAFilterFiles {
            get {
                return ResourceManager.GetString("FilterWWAFilterFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero order hold upsample: {0}x.
        /// </summary>
        internal static string FilterZOHDesc {
            get {
                return ResourceManager.GetString("FilterZOHDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Gaussian noise: {0} dB.
        /// </summary>
        internal static string GaussianNoiseDesc {
            get {
                return ResourceManager.GetString("GaussianNoiseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add octave bass unison of the sound below 80Hz.
        /// </summary>
        internal static string GroupAddFundamentals {
            get {
                return ResourceManager.GetString("GroupAddFundamentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Gaussian noise.
        /// </summary>
        internal static string GroupAddGaussianNoise {
            get {
                return ResourceManager.GetString("GroupAddGaussianNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Jitter.
        /// </summary>
        internal static string GroupAddJitter {
            get {
                return ResourceManager.GetString("GroupAddJitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIC Filter.
        /// </summary>
        internal static string GroupCic {
            get {
                return ResourceManager.GetString("GroupCic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downsampler.
        /// </summary>
        internal static string GroupDownsampler {
            get {
                return ResourceManager.GetString("GroupDownsampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Range Compression.
        /// </summary>
        internal static string GroupDynamicRangeCompression {
            get {
                return ResourceManager.GetString("GroupDynamicRangeCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter settings.
        /// </summary>
        internal static string GroupFilterSettings {
            get {
                return ResourceManager.GetString("GroupFilterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First-order All-pass IIR Filter.
        /// </summary>
        internal static string GroupFirstOrderAllPassIIR {
            get {
                return ResourceManager.GetString("GroupFirstOrderAllPassIIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        internal static string GroupGain {
            get {
                return ResourceManager.GetString("GroupGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-band Filter.
        /// </summary>
        internal static string GroupHalfbandFilter {
            get {
                return ResourceManager.GetString("GroupHalfbandFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        internal static string GroupInputFile {
            get {
                return ResourceManager.GetString("GroupInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string GroupLog {
            get {
                return ResourceManager.GetString("GroupLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIR Linear-Phase Low pass Filter.
        /// </summary>
        internal static string GroupLPF {
            get {
                return ResourceManager.GetString("GroupLPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Shaping.
        /// </summary>
        internal static string GroupNoiseShaping {
            get {
                return ResourceManager.GetString("GroupNoiseShaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalize.
        /// </summary>
        internal static string GroupNormalizeFilter {
            get {
                return ResourceManager.GetString("GroupNormalizeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        internal static string GroupOutputFile {
            get {
                return ResourceManager.GetString("GroupOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce bit depth.
        /// </summary>
        internal static string GroupReduceBitDepth {
            get {
                return ResourceManager.GetString("GroupReduceBitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second-order All-pass IIR Filter.
        /// </summary>
        internal static string GroupSecondOrderAllPassIIR {
            get {
                return ResourceManager.GetString("GroupSecondOrderAllPassIIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tag.
        /// </summary>
        internal static string GroupTagEdit {
            get {
                return ResourceManager.GetString("GroupTagEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upsampler.
        /// </summary>
        internal static string GroupUpsampler {
            get {
                return ResourceManager.GetString("GroupUpsampler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay:.
        /// </summary>
        internal static string LabelCicDelay {
            get {
                return ResourceManager.GetString("LabelCicDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to samples.
        /// </summary>
        internal static string LabelCicDelaySamples {
            get {
                return ResourceManager.GetString("LabelCicDelaySamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string LabelCicFilterType {
            get {
                return ResourceManager.GetString("LabelCicFilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutoff frequency:.
        /// </summary>
        internal static string LabelCutoffFreq {
            get {
                return ResourceManager.GetString("LabelCutoffFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option:.
        /// </summary>
        internal static string LabelDownsamplerOption {
            get {
                return ResourceManager.GetString("LabelDownsamplerOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        internal static string LabelDownsamplerType {
            get {
                return ResourceManager.GetString("LabelDownsamplerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIR filter length:.
        /// </summary>
        internal static string LabelFilterLength {
            get {
                return ResourceManager.GetString("LabelFilterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain in Amplitude:.
        /// </summary>
        internal static string LabelGainInAmplitude {
            get {
                return ResourceManager.GetString("LabelGainInAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain in dB:.
        /// </summary>
        internal static string LabelGainInDb {
            get {
                return ResourceManager.GetString("LabelGainInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain roll off slopes:.
        /// </summary>
        internal static string LabelGainRolloffSlopes {
            get {
                return ResourceManager.GetString("LabelGainRolloffSlopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter taps:.
        /// </summary>
        internal static string LabelHalfBandFilterTaps {
            get {
                return ResourceManager.GetString("LabelHalfBandFilterTaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file:.
        /// </summary>
        internal static string LabelInputFile {
            get {
                return ResourceManager.GetString("LabelInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise shaping method:.
        /// </summary>
        internal static string LabelNoiseShapingMethod {
            get {
                return ResourceManager.GetString("LabelNoiseShapingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Quantized Bit Rate:.
        /// </summary>
        internal static string LabelNoiseShapingTargetBit {
            get {
                return ResourceManager.GetString("LabelNoiseShapingTargetBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized amplitude (dBFS):.
        /// </summary>
        internal static string LabelNormalizeAmplitude {
            get {
                return ResourceManager.GetString("LabelNormalizeAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file:.
        /// </summary>
        internal static string LabelOutputFile {
            get {
                return ResourceManager.GetString("LabelOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to samples.
        /// </summary>
        internal static string LabelSamples {
            get {
                return ResourceManager.GetString("LabelSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to θ (degrees, -180 ≤ θ &lt; 180):.
        /// </summary>
        internal static string LabelSecondAllPassIirT {
            get {
                return ResourceManager.GetString("LabelSecondAllPassIirT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        internal static string LabelTagText {
            get {
                return ResourceManager.GetString("LabelTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag type:.
        /// </summary>
        internal static string LabelTagType {
            get {
                return ResourceManager.GetString("LabelTagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target bit depth (bit).
        /// </summary>
        internal static string LabelTargetBitDepth {
            get {
                return ResourceManager.GetString("LabelTargetBitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT Length:.
        /// </summary>
        internal static string LabelUpsamplerLength {
            get {
                return ResourceManager.GetString("LabelUpsamplerLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upsampler Type:.
        /// </summary>
        internal static string LabelUpsamplerType {
            get {
                return ResourceManager.GetString("LabelUpsamplerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upsampling factor:.
        /// </summary>
        internal static string LabelUpsamplingFactor {
            get {
                return ResourceManager.GetString("LabelUpsamplingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string LabelX {
            get {
                return ResourceManager.GetString("LabelX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed. Elapsed time: {0}
        ///.
        /// </summary>
        internal static string LogCompleted {
            get {
                return ResourceManager.GetString("LogCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read completed. now processing...
        ///.
        /// </summary>
        internal static string LogFileReadCompleted {
            get {
                return ResourceManager.GetString("LogFileReadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file {0} ...
        ///.
        /// </summary>
        internal static string LogFileReadStarted {
            get {
                return ResourceManager.GetString("LogFileReadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed. now writing to {0} ...
        ///.
        /// </summary>
        internal static string LogfileWriteStarted {
            get {
                return ResourceManager.GetString("LogfileWriteStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to store..
        /// </summary>
        internal static string NothingToStore {
            get {
                return ResourceManager.GetString("NothingToStore", resourceCulture);
            }
        }
    }
}
