//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWFlacRWCS.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WWFlacRWCS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   FLAC header corrupted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorBadHeader {
            get {
                return ResourceManager.GetString("FlacErrorBadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC bad parameter error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorBadParams {
            get {
                return ResourceManager.GetString("FlacErrorBadParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC buffer size mismatch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorBufferSizeMismatch {
            get {
                return ResourceManager.GetString("FlacErrorBufferSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data not ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorDataNotReady {
            get {
                return ResourceManager.GetString("FlacErrorDataNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC decoder process failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorDecoderProcessFailed {
            get {
                return ResourceManager.GetString("FlacErrorDecoderProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC encoder error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorEncoder {
            get {
                return ResourceManager.GetString("FlacErrorEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC encoder process failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorEncoderProcessFailed {
            get {
                return ResourceManager.GetString("FlacErrorEncoderProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC file read open error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorFileReadOpen {
            get {
                return ResourceManager.GetString("FlacErrorFileReadOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC frame CRC mismatch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorFrameCrcMismatch {
            get {
                return ResourceManager.GetString("FlacErrorFrameCrcMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Internal error (id not found) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorIdNotFound {
            get {
                return ResourceManager.GetString("FlacErrorIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC bits per sample error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorInvalidBitsPerSample {
            get {
                return ResourceManager.GetString("FlacErrorInvalidBitsPerSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC metadata error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorInvalidMetadata {
            get {
                return ResourceManager.GetString("FlacErrorInvalidMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC number of channels is invalid (must be smaller than or equal to 8) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorInvalidNumberOfChannels {
            get {
                return ResourceManager.GetString("FlacErrorInvalidNumberOfChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC sample rate is out of range (must be smaller than or equal to 655,350Hz) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorInvalidSampleRate {
            get {
                return ResourceManager.GetString("FlacErrorInvalidSampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC lost sync error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorLostSync {
            get {
                return ResourceManager.GetString("FlacErrorLostSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC memory exhausted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorMemoryExhausted {
            get {
                return ResourceManager.GetString("FlacErrorMemoryExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC number of frames is not aligned に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorNumFrameIsNotAligned {
            get {
                return ResourceManager.GetString("FlacErrorNumFrameIsNotAligned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC other error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorOther {
            get {
                return ResourceManager.GetString("FlacErrorOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output data size exceeds 2GB per channel! Process aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorOutputFileTooLarge {
            get {
                return ResourceManager.GetString("FlacErrorOutputFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC receive buffer size is insufficient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorRecvBufferSizeInsufficient {
            get {
                return ResourceManager.GetString("FlacErrorRecvBufferSizeInsufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC stream decoder init failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorStreamDecoderInitFailed {
            get {
                return ResourceManager.GetString("FlacErrorStreamDecoderInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC stream decoder new failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorStreamDecoderNewFailed {
            get {
                return ResourceManager.GetString("FlacErrorStreamDecoderNewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FLAC unparseable error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacErrorUnparseable {
            get {
                return ResourceManager.GetString("FlacErrorUnparseable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write open failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlacerrorWriteOpenFailed {
            get {
                return ResourceManager.GetString("FlacerrorWriteOpenFailed", resourceCulture);
            }
        }
    }
}
