//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWUserControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WWUserControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C of stage #{0} = {1}.
        /// </summary>
        internal static string CapacitorValueDescription {
            get {
                return ResourceManager.GetString("CapacitorValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Release time must be integer equal to or larger than zero.
        /// </summary>
        internal static string ErrorReleaseTimeMustBePositiveInteger {
            get {
                return ResourceManager.GetString("ErrorReleaseTimeMustBePositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        internal static string MainLevelMeterOther {
            get {
                return ResourceManager.GetString("MainLevelMeterOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release time.
        /// </summary>
        internal static string MainLevelMeterReleaseTime {
            get {
                return ResourceManager.GetString("MainLevelMeterReleaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amber Level.
        /// </summary>
        internal static string MainNominalPeakLevel {
            get {
                return ResourceManager.GetString("MainNominalPeakLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Hold.
        /// </summary>
        internal static string MainPeakHold {
            get {
                return ResourceManager.GetString("MainPeakHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R of stage #{0} = {1}.
        /// </summary>
        internal static string ResistorValueDescription {
            get {
                return ResourceManager.GetString("ResistorValueDescription", resourceCulture);
            }
        }
    }
}
